import * as stylex from '@stylexjs/stylex';
import { contentStyles } from './stylex-content.js';
import { foundationStyles } from './stylex-foundation.js';
import { mediaStyles } from './stylex-media.js';
import { quizStyles } from './stylex-quiz.js';
import { taskStyles } from './stylex-tasks.js';

export const styles = {
  ...foundationStyles,
  ...contentStyles,
  ...mediaStyles,
  ...quizStyles,
  ...taskStyles
};

const aliases = {
  shell: 'shell',
  topbar: 'topbar',
  'workspace-topbar': 'workspaceTopbar',
  'brand-mark': 'brandMark',
  'brand-name': 'brandName',
  'topbar-status': 'topbarStatus',
  'status-dot': 'statusDot',
  'back-button': 'backButton',
  'back-label': 'backLabel',
  'titlebar-name': 'titlebarName',
  'titlebar-dot': 'titlebarDot',
  'window-actions': 'windowActions',
  'close-button': 'closeButton',
  rail: 'rail',
  tab: 'tab',
  'tab-glyph': 'tabGlyph',
  'tab-label': 'tabLabel',
  'tab-dot': 'tabDot',
  'tools-panel': 'sidePanel',
  'quiz-panel': 'sidePanel',
  'tools-group-label': 'groupLabel',
  'tools-item': 'sideItem',
  'tools-item-glyph': 'sideGlyph',
  'tools-item-copy': 'sideCopy',
  'quiz-shell': 'quizShell',
  'quiz-layout': 'quizLayout',
  'map-page': 'mapPage',
  'map-layout': 'mapLayout',
  'map-panel': 'mapPanel',
  'map-panel-heading': 'mapPanelHeading',
  'map-panel-actions': 'mapPanelActions',
  'map-reset': 'mapReset',
  'map-count': 'mapCount',
  'map-toolbar': 'mapToolbar',
  'map-mode': 'mapMode',
  'map-mode-button': 'mapModeButton',
  'map-select-wrap': 'mapSelectWrap',
  'map-select': 'mapSelect',
  'map-canvas': 'mapCanvas',
  'map-leaflet': 'mapLeaflet',
  'map-overlay': 'mapOverlay',
  'map-overlay-kicker': 'mapOverlayKicker',
  'map-footer': 'mapFooter',
  'map-source-mark': 'mapSourceMark',
  'map-browser': 'mapBrowser',
  'map-browser-heading': 'mapBrowserHeading',
  'map-search-wrap': 'mapSearchWrap',
  'map-search': 'mapSearch',
  'map-list': 'mapList',
  'map-list-item': 'mapListItem',
  'map-list-color': 'mapListColor',
  'map-list-copy': 'mapListCopy',
  'map-list-chevron': 'mapListChevron',
  'map-empty': 'mapEmpty',
  'map-data-panel': 'mapDataPanel',
  'map-data-heading': 'mapDataHeading',
  'map-table-scroll': 'mapTableScroll',
  'map-table': 'mapTable',
  'map-table-head': 'mapTableHead',
  'map-table-cell': 'mapTableCell',
  'map-table-detail': 'mapTableDetail',
  'map-table-row': 'mapTableRow',
  'map-table-action': 'mapTableAction',
  'map-table-action-name': 'mapTableActionName',
  'map-table-empty': 'mapTableEmpty',
  'map-selection': 'mapSelection',
  'map-selection-type': 'mapSelectionType',
  'map-selection-name': 'mapSelectionName',
  'map-source': 'mapSource',
  'quiz-header': 'quizHeader',
  'quiz-score': 'quizScore',
  'quiz-collection-row': 'quizCollection',
  'quiz-editor-toolbar': 'quizToolbar',
  'quiz-editor-summary': 'quizSummary',
  'quiz-editor-list': 'quizEditorList',
  'quiz-editor-row': 'quizEditorRow',
  'quiz-editor-number': 'quizNumber',
  'quiz-select-wrap': 'sideCopy',
  'quiz-search': 'searchInput',
  'quiz-collection-mark': 'quizMark',
  'quiz-collection-copy': 'quizCopy',
  'quiz-reset-button': 'quizButton',
  'quiz-secondary-button': 'quizButton',
  'quiz-known-button': 'quizButton',
  'quiz-primary-button': 'quizButton',
  'quiz-reveal': 'quizButton',
  'quiz-progress': 'quizProgress',
  'quiz-progress-track': 'quizProgressTrack',
  'quiz-main-grid': 'quizGrid',
  'quiz-card': 'quizCard',
  'quiz-index-card': 'quizIndex',
  'quiz-card-topline': 'quizTopline',
  'quiz-difficulty': 'difficulty',
  'quiz-card-kicker': 'quizKicker',
  'quiz-answer': 'quizAnswer',
  'quiz-answer-label': 'quizAnswerLabel',
  'quiz-explanation': 'quizExplanation',
  'quiz-card-actions': 'quizActions',
  'quiz-question-list': 'quizQuestions',
  'quiz-question-row': 'quizQuestion',
  'quiz-empty': 'empty',
  'launcher-main': 'launcher',
  'launcher-head': 'toolHeading',
  'tool-list': 'toolList',
  'tool-row': 'toolRow',
  'row-glyph': 'rowGlyph',
  'row-copy': 'rowCopy',
  'row-chevron': 'rowChevron',
  'launcher-status': 'launcherStatus',
  'recent-strip': 'recent',
  chip: 'chip',
  error: 'error',
  'workspace-error': 'workspaceError',
  'workspace-body': 'workspaceBody',
  'tool-page': 'toolPage',
  eyebrow: 'eyebrow',
  lede: 'lede',
  'error-title': 'errorTitle',
  'tool-heading': 'toolHeading',
  'mock-badge': 'badge',
  'tool-panel': 'panel',
  'panel-heading': 'panelHeading',
  'panel-label': 'panelLabel',
  'panel-status': 'panelStatus',
  'select-label': 'selectLabel',
  select: 'select',
  'panel-note': 'note',
  'disk-grid': 'diskGrid',
  'volume-summary': 'summaryRow',
  'progress-track': 'bar',
  'primary-button': 'primary',
  'folder-list': 'folderList',
  'folder-copy': 'folderCopy',
  'storage-footer': 'footerRow',
  'notes-layout': 'notesLayout',
  'notes-list-panel': 'notesPanel',
  'note-editor': 'editor',
  'notes-list-heading': 'headingRow',
  'new-note-button': 'action',
  'export-button': 'action',
  'search-field': 'searchInput',
  'search-engine-note': 'searchEngineNote',
  'notes-list': 'notesList',
  'note-list-item': 'noteItem',
  'note-list-meta': 'noteMeta',
  'note-list-updated': 'noteUpdated',
  'empty-notes': 'empty',
  'note-editor-heading': 'headingRow',
  'note-saved': 'saved',
  'note-title-input': 'titleInput',
  'note-meta-row': 'metaRow',
  'note-body-input': 'bodyInput',
  'qna-field': 'qnaField',
  'qna-label': 'qnaLabel',
  'qna-input': 'qnaInput',
  'qna-question-input': 'qnaQuestionInput',
  'qna-answer-input': 'qnaAnswerInput',
  'qna-import': 'qnaImport',
  'qna-help': 'qnaHelp',
  'qna-import-input': 'qnaImportInput',
  'note-editor-footer': 'editorFooter',
  'text-button': 'textButton',
  'audio-console': 'audioConsole',
  'track-meta': 'trackMeta',
  'album-art': 'albumArt',
  'track-source': 'muted',
  'toggle-button': 'toggle',
  visualizer: 'visualizer',
  'transport-row': 'transport',
  'transport-track': 'transportTrack',
  bands: 'bands',
  band: 'band',
  'band-value': 'bandValue',
  'band-label': 'bandLabel',
  'master-row': 'master',
  'presets-panel': 'presets',
  'preset-list': 'presetList',
  'backend-status': 'backendStatus',
  'backend-status-label': 'backendLabel',
  'backend-status-value': 'backendValue',
  'backend-status-actions': 'backendActions',
  'backend-status-error': 'backendError',
  'toggle-all': 'todoToggleAll',
  'todo-list': 'todoList',
  'todo-checkbox': 'todoCheckbox',
  'todo-filters': 'todoFilters',
  'sr-only': 'srOnly'
};

export function sx(...classNames) {
  const values = classNames.flatMap((value) => {
    if (value && typeof value === 'object') return [value];
    return String(value || '')
      .split(/\s+/)
      .map((name) => {
        const camelName = name.replace(/-([a-z])/g, (_, letter) =>
          letter.toUpperCase()
        );
        return styles[aliases[name] || camelName];
      })
      .filter(Boolean);
  });
  return stylex.props(...values).className;
}

export function toneStyle(tone, variant = '') {
  if (tone === 'violet') tone = 'purple';
  if (variant === true) variant = 'mark';
  const suffix = variant ? variant[0].toUpperCase() + variant.slice(1) : '';
  const name = `${tone[0].toUpperCase()}${tone.slice(1)}${suffix}`;
  return styles[name] || styles.gold;
}
